# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.classicarcadeprojects.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Classic Arcade Projects
  avatar: 
  gravatar: #959080cbb338fac79169ebbe21cbe988
  description: "Dedicated to my classic arcade build and rebuild projects" # used by search engines

  # Header and footer text
  header_text: >
     <p>Adventures in Classic Arcade Gaming</p>
  header_text_feature_image:
  footer_text: >
   <a href="/about">About</a> | <a href="/privacy">Privacy Policy</a> | <a href="/sitemap.xml">Sitemap</a>

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: #"rohanchandra/type-theme"
  google_plus: 
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: #"twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-79200937-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup
  muut_community_name: "classicarcadeprojects"

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more"
  str_comments: "Comments"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]

# SITEMAP GENERATOR
# https://github.com/jekyll/jekyll-sitemap
gems:
  - jekyll-sitemap
  
# MAKES IT WORK LOCALLY
exclude: [vendor]
